const wordData3 = [
  // === Advanced Verbs (501-550) ===
  { word: "negotiate", meaning: "交渉する", example: "We need to negotiate the contract terms." },
  { word: "persuade", meaning: "説得する", example: "She persuaded him to change his mind." },
  { word: "compromise", meaning: "妥協する", example: "Both sides had to compromise to reach a deal." },
  { word: "anticipate", meaning: "予測する・期待する", example: "We anticipate strong demand for this product." },
  { word: "accommodate", meaning: "収容する・対応する", example: "The hotel can accommodate up to 300 guests." },
  { word: "acknowledge", meaning: "認める・認知する", example: "He acknowledged his mistake and apologized." },
  { word: "implement", meaning: "実施する・導入する", example: "We will implement the new system next month." },
  { word: "allocate", meaning: "割り当てる・配分する", example: "The company allocated funds for research." },
  { word: "contradict", meaning: "矛盾する・反論する", example: "His actions contradict his words." },
  { word: "diminish", meaning: "減少させる・弱める", example: "Nothing can diminish her enthusiasm." },
  { word: "elaborate", meaning: "詳しく説明する", example: "Could you elaborate on your proposal?" },
  { word: "enforce", meaning: "施行する・強制する", example: "The police enforce traffic laws strictly." },
  { word: "extract", meaning: "抽出する・引き出す", example: "They extract oil from deep underground." },
  { word: "fluctuate", meaning: "変動する", example: "Prices fluctuate depending on supply and demand." },
  { word: "incorporate", meaning: "組み込む・取り入れる", example: "We incorporated customer feedback into the design." },
  { word: "intensify", meaning: "強化する・激しくなる", example: "The storm is expected to intensify overnight." },
  { word: "intervene", meaning: "介入する・仲裁する", example: "The government decided to intervene in the crisis." },
  { word: "legitimate", meaning: "正当化する・合法的な", example: "He tried to legitimate his unusual decision." },
  { word: "manipulate", meaning: "操作する・巧みに扱う", example: "He tried to manipulate the data to hide the error." },
  { word: "notify", meaning: "通知する・知らせる", example: "Please notify us of any changes in advance." },
  { word: "overcome", meaning: "克服する・打ち勝つ", example: "She overcame many obstacles to achieve her goal." },
  { word: "perceive", meaning: "認識する・気づく", example: "People perceive risk differently depending on experience." },
  { word: "postpone", meaning: "延期する", example: "We had to postpone the meeting until Friday." },
  { word: "reinforce", meaning: "補強する・強化する", example: "The training reinforced what we learned in class." },
  { word: "speculate", meaning: "推測する・投機する", example: "Analysts speculate that the economy will recover soon." },
  { word: "stimulate", meaning: "刺激する・活性化する", example: "Coffee stimulates the brain and increases alertness." },
  { word: "substitute", meaning: "代用する・代わりにする", example: "You can substitute honey for sugar in this recipe." },
  { word: "suspend", meaning: "一時停止する・中断する", example: "The company suspended operations during the storm." },
  { word: "tolerate", meaning: "耐える・許容する", example: "I cannot tolerate rude behavior." },
  { word: "undergo", meaning: "経験する・受ける", example: "The building will undergo major renovations." },
  { word: "utilize", meaning: "活用する・利用する", example: "We should utilize all available resources." },
  { word: "violate", meaning: "違反する・侵害する", example: "He was fined for violating traffic regulations." },
  { word: "withdraw", meaning: "引き出す・撤退する", example: "She withdrew money from her savings account." },
  { word: "accumulate", meaning: "蓄積する・積み重なる", example: "Dust accumulates quickly if you don't clean regularly." },
  { word: "adapt", meaning: "適応する・順応する", example: "You need to adapt to the new working environment." },
  { word: "alleviate", meaning: "緩和する・軽減する", example: "This medicine will alleviate your pain." },
  { word: "assert", meaning: "主張する・断言する", example: "She asserted her right to speak at the meeting." },
  { word: "coincide", meaning: "一致する・同時に起こる", example: "The festival coincides with the national holiday." },
  { word: "compensate", meaning: "補償する・埋め合わせる", example: "The company compensated employees for overtime work." },
  { word: "deprive", meaning: "奪う・取り上げる", example: "The war deprived many children of education." },
  { word: "deteriorate", meaning: "悪化する・劣化する", example: "His health deteriorated rapidly after the accident." },
  { word: "exaggerate", meaning: "誇張する・大げさに言う", example: "Don't exaggerate — it wasn't that bad." },
  { word: "exhibit", meaning: "展示する・示す", example: "The museum exhibits paintings from the 19th century." },
  { word: "inhibit", meaning: "抑制する・妨げる", example: "Fear can inhibit creativity and innovation." },
  { word: "commence", meaning: "開始する", example: "The ceremony will commence at ten o'clock." },
  { word: "comply", meaning: "従う・遵守する", example: "All employees must comply with company policies." },
  { word: "confine", meaning: "制限する・閉じ込める", example: "Please confine your remarks to the topic." },
  { word: "convey", meaning: "伝える・運ぶ", example: "Words cannot convey how grateful I am." },
  { word: "devote", meaning: "捧げる・専念する", example: "She devoted her life to helping others." },
  { word: "disclose", meaning: "開示する・明らかにする", example: "The company disclosed its financial results." },
  // === Business & Professional (551-590) ===
  { word: "revenue", meaning: "収益・売上", example: "The company's revenue increased by 20% this year." },
  { word: "stakeholder", meaning: "利害関係者", example: "We must consider the interests of all stakeholders." },
  { word: "merger", meaning: "合併", example: "The merger of the two companies created a giant corporation." },
  { word: "acquisition", meaning: "買収・取得", example: "The acquisition of the startup cost $5 million." },
  { word: "dividend", meaning: "配当金", example: "Shareholders received a generous dividend this quarter." },
  { word: "audit", meaning: "監査・会計検査", example: "The firm conducts an annual financial audit." },
  { word: "liability", meaning: "負債・責任", example: "The company has significant liabilities on its balance sheet." },
  { word: "equity", meaning: "株式・自己資本・公平", example: "They offered equity in the company to early employees." },
  { word: "benchmark", meaning: "基準・ベンチマーク", example: "This score serves as a benchmark for future performance." },
  { word: "outsource", meaning: "外部委託する", example: "Many companies outsource customer service to reduce costs." },
  { word: "invoice", meaning: "請求書", example: "Please send the invoice by the end of the month." },
  { word: "quota", meaning: "割り当て・ノルマ", example: "Each salesperson has a monthly quota to meet." },
  { word: "fiscal", meaning: "財政の・会計の", example: "The fiscal year ends in March for many Japanese companies." },
  { word: "procurement", meaning: "調達", example: "The procurement department handles all purchasing." },
  { word: "compliance", meaning: "法令遵守・コンプライアンス", example: "Compliance with regulations is mandatory for all staff." },
  { word: "portfolio", meaning: "ポートフォリオ・資産構成", example: "She diversified her investment portfolio." },
  { word: "subsidiary", meaning: "子会社", example: "The subsidiary operates independently from the parent company." },
  { word: "monopoly", meaning: "独占", example: "The government broke up the company's monopoly." },
  { word: "leverage", meaning: "てこ・影響力・活用する", example: "We can leverage our brand to enter new markets." },
  { word: "entrepreneur", meaning: "起業家", example: "The young entrepreneur started her own tech company." },
  { word: "restructure", meaning: "再構築する・組織変更する", example: "The company plans to restructure its management team." },
  { word: "commodity", meaning: "商品・日用品", example: "Oil is one of the most traded commodities in the world." },
  { word: "delegation", meaning: "代表団・権限委譲", example: "A delegation from Japan attended the summit." },
  { word: "turnover", meaning: "売上高・離職率", example: "High employee turnover is a problem for the company." },
  { word: "overhead", meaning: "諸経費・間接費", example: "We need to reduce overhead costs to improve profitability." },
  { word: "breakeven", meaning: "損益分岐点", example: "The project will reach breakeven within two years." },
  { word: "recession", meaning: "景気後退・不況", example: "The economy entered a recession after the financial crisis." },
  { word: "inflation", meaning: "インフレ・物価上昇", example: "Inflation has driven up the cost of living." },
  { word: "mortgage", meaning: "住宅ローン・抵当", example: "They took out a mortgage to buy their first house." },
  { word: "franchise", meaning: "フランチャイズ・営業権", example: "He opened a franchise of a popular restaurant chain." },
  { word: "prospectus", meaning: "目論見書・案内書", example: "Investors should read the prospectus carefully." },
  { word: "liquidate", meaning: "清算する・現金化する", example: "The company was forced to liquidate its assets." },
  { word: "arbitration", meaning: "仲裁・調停", example: "The dispute was settled through arbitration." },
  { word: "consortium", meaning: "共同事業体・コンソーシアム", example: "A consortium of banks funded the project." },
  { word: "depreciation", meaning: "減価償却・価値低下", example: "The depreciation of equipment is recorded annually." },
  { word: "collateral", meaning: "担保", example: "The bank requires collateral for large loans." },
  { word: "tariff", meaning: "関税", example: "The government imposed tariffs on imported goods." },
  { word: "subsidy", meaning: "補助金・助成金", example: "Farmers receive subsidies from the government." },
  { word: "inventory", meaning: "在庫・棚卸し", example: "We need to check our inventory before placing an order." },
  { word: "logistics", meaning: "物流・ロジスティクス", example: "Efficient logistics are essential for global trade." },
  // === Academic & Learning (591-620) ===
  { word: "hypothesis", meaning: "仮説", example: "The scientist tested her hypothesis through experiments." },
  { word: "thesis", meaning: "論文・学位論文", example: "She is writing her master's thesis on climate change." },
  { word: "curriculum", meaning: "教育課程・カリキュラム", example: "The school updated its curriculum to include coding." },
  { word: "bibliography", meaning: "参考文献一覧", example: "Include a bibliography at the end of your paper." },
  { word: "plagiarism", meaning: "盗用・剽窃", example: "Plagiarism is a serious offense in academic writing." },
  { word: "symposium", meaning: "シンポジウム・学術会議", example: "Researchers gathered for an international symposium." },
  { word: "dissertation", meaning: "博士論文", example: "He defended his dissertation before the committee." },
  { word: "methodology", meaning: "方法論", example: "The methodology section explains how the research was conducted." },
  { word: "empirical", meaning: "実証的な・経験的な", example: "The study is based on empirical evidence." },
  { word: "abstract", meaning: "要旨・抽象的な", example: "Read the abstract before deciding to read the full paper." },
  { word: "peer", meaning: "同僚・同等の人", example: "The paper was reviewed by her peers in the field." },
  { word: "citation", meaning: "引用", example: "Proper citation is essential in academic writing." },
  { word: "enrollment", meaning: "入学・登録", example: "Enrollment in the course begins next week." },
  { word: "prerequisite", meaning: "前提条件・必要条件", example: "Math 101 is a prerequisite for this advanced course." },
  { word: "scholarship", meaning: "奨学金", example: "She won a scholarship to study abroad." },
  { word: "syllabus", meaning: "シラバス・授業計画", example: "The professor handed out the syllabus on the first day." },
  { word: "tuition", meaning: "授業料", example: "Tuition fees have increased significantly over the years." },
  { word: "seminar", meaning: "セミナー・ゼミ", example: "I attended a seminar on artificial intelligence." },
  { word: "undergraduate", meaning: "学部生・学部の", example: "She is an undergraduate student majoring in biology." },
  { word: "postgraduate", meaning: "大学院生・大学院の", example: "He is pursuing postgraduate studies in engineering." },
  { word: "literacy", meaning: "読み書き能力・リテラシー", example: "Digital literacy is essential in the modern workplace." },
  { word: "cognitive", meaning: "認知の", example: "Cognitive abilities decline with age in some areas." },
  { word: "pedagogy", meaning: "教育学・教授法", example: "Modern pedagogy emphasizes active learning." },
  { word: "analytical", meaning: "分析的な", example: "Analytical thinking is a valuable skill in any profession." },
  { word: "discourse", meaning: "談話・論述", example: "Academic discourse requires precise language." },
  { word: "profound", meaning: "深い・深遠な", example: "The book had a profound impact on my thinking." },
  { word: "rigorous", meaning: "厳密な・厳格な", example: "The program requires rigorous academic standards." },
  { word: "coherent", meaning: "首尾一貫した・論理的な", example: "Your argument needs to be more coherent." },
  { word: "ambiguous", meaning: "曖昧な", example: "The instructions were ambiguous and caused confusion." },
  { word: "cumulative", meaning: "累積的な", example: "The cumulative effect of stress can be harmful." },
  // === Social & Relationships (621-650) ===
  { word: "empathy", meaning: "共感・感情移入", example: "Showing empathy helps build strong relationships." },
  { word: "intimacy", meaning: "親密さ・親しさ", example: "Trust is the foundation of intimacy in a relationship." },
  { word: "prejudice", meaning: "偏見・先入観", example: "We should fight against prejudice and discrimination." },
  { word: "stereotype", meaning: "固定観念・ステレオタイプ", example: "We should avoid stereotypes about other cultures." },
  { word: "etiquette", meaning: "礼儀作法・エチケット", example: "Business etiquette varies from country to country." },
  { word: "obligation", meaning: "義務・責任", example: "Parents have an obligation to care for their children." },
  { word: "reconcile", meaning: "和解する・調和させる", example: "The couple tried to reconcile after their argument." },
  { word: "solidarity", meaning: "連帯・団結", example: "The community showed solidarity during the crisis." },
  { word: "altruism", meaning: "利他主義", example: "Her altruism inspired others to volunteer." },
  { word: "consent", meaning: "同意・承諾", example: "You need written consent from the patient." },
  { word: "dignity", meaning: "尊厳・威厳", example: "Every person deserves to be treated with dignity." },
  { word: "harassment", meaning: "ハラスメント・嫌がらせ", example: "The company has a strict policy against harassment." },
  { word: "mediate", meaning: "仲介する・調停する", example: "A neutral party was asked to mediate the dispute." },
  { word: "nurture", meaning: "育てる・養育する", example: "Parents nurture their children with love and patience." },
  { word: "resent", meaning: "恨む・憤慨する", example: "She resented being treated unfairly by her boss." },
  { word: "sympathize", meaning: "同情する・共感する", example: "I sympathize with your situation." },
  { word: "betray", meaning: "裏切る", example: "He felt betrayed when his friend shared his secret." },
  { word: "confide", meaning: "打ち明ける・信頼して話す", example: "She confided in her best friend about her worries." },
  { word: "confront", meaning: "直面する・立ち向かう", example: "You should confront the problem instead of avoiding it." },
  { word: "dominate", meaning: "支配する・優位に立つ", example: "One player dominated the entire game." },
  { word: "embrace", meaning: "抱きしめる・受け入れる", example: "We should embrace diversity in the workplace." },
  { word: "flatter", meaning: "お世辞を言う・おだてる", example: "Don't flatter me — just tell me the truth." },
  { word: "gossip", meaning: "うわさ話・噂をする", example: "Office gossip can damage team morale." },
  { word: "humiliate", meaning: "恥をかかせる・屈辱を与える", example: "No one has the right to humiliate another person." },
  { word: "isolate", meaning: "孤立させる・隔離する", example: "Don't isolate yourself — talk to someone you trust." },
  { word: "bond", meaning: "絆・結びつき", example: "The shared experience created a strong bond between them." },
  { word: "courtesy", meaning: "礼儀・丁重さ", example: "He opened the door as a courtesy." },
  { word: "mutual", meaning: "相互の・共通の", example: "They have a mutual respect for each other." },
  { word: "peer pressure", meaning: "同調圧力", example: "Teenagers often struggle with peer pressure." },
  { word: "rapport", meaning: "信頼関係", example: "Building rapport with clients is essential for success." },
  // === Law & Society (651-680) ===
  { word: "legislation", meaning: "法律・立法", example: "New legislation was introduced to protect consumers." },
  { word: "verdict", meaning: "評決・判決", example: "The jury reached a unanimous verdict of not guilty." },
  { word: "plaintiff", meaning: "原告", example: "The plaintiff filed a lawsuit against the company." },
  { word: "defendant", meaning: "被告", example: "The defendant pleaded not guilty to all charges." },
  { word: "statute", meaning: "法令・制定法", example: "The statute limits the maximum working hours per week." },
  { word: "jurisdiction", meaning: "管轄権・司法権", example: "This case falls under federal jurisdiction." },
  { word: "amendment", meaning: "修正・改正", example: "The amendment to the constitution was approved." },
  { word: "prosecution", meaning: "起訴・検察", example: "The prosecution presented strong evidence." },
  { word: "testimony", meaning: "証言", example: "The witness gave testimony under oath." },
  { word: "sanction", meaning: "制裁・認可", example: "Economic sanctions were imposed on the country." },
  { word: "indict", meaning: "起訴する", example: "The grand jury decided to indict the suspect." },
  { word: "acquit", meaning: "無罪にする・放免する", example: "The jury acquitted the defendant of all charges." },
  { word: "allegation", meaning: "申し立て・主張", example: "He denied the allegations of fraud." },
  { word: "advocacy", meaning: "支持・擁護活動", example: "She is known for her advocacy of human rights." },
  { word: "bureaucracy", meaning: "官僚制度・官僚主義", example: "Bureaucracy often slows down decision-making." },
  { word: "constitution", meaning: "憲法", example: "The constitution guarantees freedom of speech." },
  { word: "corruption", meaning: "汚職・腐敗", example: "The government promised to fight corruption." },
  { word: "democracy", meaning: "民主主義", example: "Democracy requires active participation from citizens." },
  { word: "diplomacy", meaning: "外交", example: "Diplomacy is essential for resolving international conflicts." },
  { word: "emigrate", meaning: "移住する（国外へ）", example: "Many people emigrated to find better opportunities." },
  { word: "asylum", meaning: "亡命・政治的庇護", example: "The refugees applied for asylum in the neighboring country." },
  { word: "referendum", meaning: "国民投票", example: "The country held a referendum on the new policy." },
  { word: "sovereignty", meaning: "主権", example: "Every nation has the right to sovereignty." },
  { word: "tribunal", meaning: "裁判所・法廷", example: "The case was brought before an international tribunal." },
  { word: "civil", meaning: "市民の・民事の", example: "Civil rights are protected by law." },
  { word: "petition", meaning: "請願・嘆願書", example: "They signed a petition against the new policy." },
  { word: "welfare", meaning: "福祉・幸福", example: "The government provides welfare programs for low-income families." },
  { word: "census", meaning: "国勢調査", example: "The census is conducted every ten years." },
  { word: "veto", meaning: "拒否権・拒否する", example: "The president used his veto power to block the bill." },
  { word: "inaugural", meaning: "就任の・最初の", example: "The president delivered an inaugural address." },
  // === Advanced Adjectives (681-710) ===
  { word: "inevitable", meaning: "避けられない・必然の", example: "Change is inevitable in any growing organization." },
  { word: "meticulous", meaning: "几帳面な・細心の", example: "She is meticulous about keeping records." },
  { word: "prevalent", meaning: "広く行き渡った・流行している", example: "Smartphone use is prevalent among young people." },
  { word: "robust", meaning: "頑丈な・力強い", example: "The company reported robust growth this quarter." },
  { word: "subtle", meaning: "微妙な・繊細な", example: "There is a subtle difference between the two words." },
  { word: "tangible", meaning: "具体的な・有形の", example: "We need tangible evidence to support this claim." },
  { word: "versatile", meaning: "多才な・万能な", example: "She is a versatile musician who plays many instruments." },
  { word: "vulnerable", meaning: "脆弱な・傷つきやすい", example: "Children are especially vulnerable to the effects of pollution." },
  { word: "ambivalent", meaning: "相反する感情の・両価的な", example: "He felt ambivalent about accepting the job offer." },
  { word: "compelling", meaning: "説得力のある・やむにやまれぬ", example: "She made a compelling argument for the new policy." },
  { word: "comprehensive", meaning: "包括的な・総合的な", example: "We offer comprehensive insurance coverage." },
  { word: "concise", meaning: "簡潔な", example: "Please keep your report concise and to the point." },
  { word: "detrimental", meaning: "有害な・不利な", example: "Smoking is detrimental to your health." },
  { word: "feasible", meaning: "実行可能な", example: "Is this plan feasible within our budget?" },
  { word: "futile", meaning: "無駄な・無益な", example: "It would be futile to argue with him." },
  { word: "imminent", meaning: "差し迫った・目前の", example: "The storm is imminent — take shelter now." },
  { word: "indispensable", meaning: "不可欠な", example: "Good communication skills are indispensable in business." },
  { word: "negligible", meaning: "無視できるほどの・取るに足らない", example: "The difference in price is negligible." },
  { word: "obsolete", meaning: "時代遅れの・廃れた", example: "This technology has become obsolete." },
  { word: "plausible", meaning: "もっともらしい", example: "His explanation sounded plausible but was actually false." },
  { word: "provisional", meaning: "暫定的な・仮の", example: "We reached a provisional agreement pending final approval." },
  { word: "redundant", meaning: "余分な・冗長な", example: "The sentence contains redundant words that should be removed." },
  { word: "skeptical", meaning: "懐疑的な", example: "Many people are skeptical about the new treatment." },
  { word: "spontaneous", meaning: "自発的な・自然発生的な", example: "The audience broke into spontaneous applause." },
  { word: "stringent", meaning: "厳しい・厳格な", example: "The factory must meet stringent safety standards." },
  { word: "superficial", meaning: "表面的な・浅い", example: "His understanding of the topic is superficial." },
  { word: "trivial", meaning: "些細な・取るに足らない", example: "Don't worry about such trivial matters." },
  { word: "unanimous", meaning: "全員一致の", example: "The decision was unanimous among all board members." },
  { word: "unprecedented", meaning: "前例のない", example: "The pandemic caused unprecedented economic disruption." },
  { word: "volatile", meaning: "不安定な・変わりやすい", example: "The stock market has been volatile recently." },
  // === Phrasal Verbs & Idioms (711-740) ===
  { word: "break down", meaning: "故障する・分解する", example: "My car broke down on the highway." },
  { word: "bring up", meaning: "育てる・話題に出す", example: "She was brought up by her grandparents." },
  { word: "call off", meaning: "中止する", example: "They called off the event due to bad weather." },
  { word: "carry out", meaning: "実行する・遂行する", example: "The team carried out the experiment successfully." },
  { word: "come across", meaning: "偶然見つける", example: "I came across an interesting article online." },
  { word: "cut back", meaning: "削減する", example: "We need to cut back on unnecessary expenses." },
  { word: "figure out", meaning: "理解する・解決する", example: "I can't figure out how to use this software." },
  { word: "get along", meaning: "仲良くやる", example: "She gets along well with her colleagues." },
  { word: "give in", meaning: "屈する・諦める", example: "He finally gave in to their demands." },
  { word: "hold up", meaning: "遅らせる・持ちこたえる", example: "The traffic accident held up our delivery." },
  { word: "keep up with", meaning: "遅れないようについていく", example: "It's hard to keep up with technological changes." },
  { word: "look into", meaning: "調査する", example: "We will look into the matter immediately." },
  { word: "make up for", meaning: "埋め合わせをする", example: "He worked overtime to make up for the lost time." },
  { word: "put off", meaning: "延期する・先延ばしにする", example: "Don't put off important tasks until tomorrow." },
  { word: "run out of", meaning: "使い果たす・なくなる", example: "We've run out of printer paper." },
  { word: "set up", meaning: "設立する・準備する", example: "They set up a new branch in Osaka." },
  { word: "stand for", meaning: "〜を表す・支持する", example: "What does this abbreviation stand for?" },
  { word: "take over", meaning: "引き継ぐ・買収する", example: "She will take over as project manager next month." },
  { word: "turn down", meaning: "断る・音量を下げる", example: "He turned down the job offer for personal reasons." },
  { word: "work out", meaning: "うまくいく・運動する", example: "Everything worked out in the end." },
  { word: "back up", meaning: "支持する・バックアップする", example: "Always back up your files regularly." },
  { word: "catch up", meaning: "追いつく", example: "I need to catch up on my reading." },
  { word: "drop off", meaning: "届ける・（数が）減る", example: "Can you drop off the package at the post office?" },
  { word: "fall behind", meaning: "遅れをとる", example: "If you miss classes, you'll fall behind." },
  { word: "hand in", meaning: "提出する", example: "Please hand in your assignment by Friday." },
  { word: "lay off", meaning: "解雇する・一時解雇する", example: "The company laid off 200 workers." },
  { word: "narrow down", meaning: "絞り込む", example: "We need to narrow down the list of candidates." },
  { word: "opt out", meaning: "参加しないことを選ぶ", example: "You can opt out of the mailing list at any time." },
  { word: "phase out", meaning: "段階的に廃止する", example: "The old system will be phased out by next year." },
  { word: "sort out", meaning: "解決する・整理する", example: "We need to sort out the scheduling conflict." },
  // === Miscellaneous Useful Words (741-750) ===
  { word: "dilemma", meaning: "ジレンマ・板挟み", example: "She faced a dilemma between career and family." },
  { word: "nuance", meaning: "ニュアンス・微妙な違い", example: "There are subtle nuances in meaning between the two words." },
  { word: "paradigm", meaning: "パラダイム・模範", example: "The internet created a paradigm shift in communication." },
  { word: "paradox", meaning: "逆説・矛盾", example: "It's a paradox that the busiest people often find time to help." },
  { word: "catalyst", meaning: "触媒・きっかけ", example: "The event served as a catalyst for social change." },
  { word: "anecdote", meaning: "逸話・エピソード", example: "He shared an amusing anecdote from his childhood." },
  { word: "analogy", meaning: "類似・たとえ", example: "She used an analogy to explain the complex concept." },
  { word: "consensus", meaning: "合意・総意", example: "The team reached a consensus on the new strategy." },
  { word: "rhetoric", meaning: "修辞学・レトリック", example: "His speech was full of powerful rhetoric." },
  { word: "trajectory", meaning: "軌道・進路", example: "The company is on an upward trajectory." }
];
