const wordData2 = [
  // --- Nature & Weather (251-280) ---
  { word: "environment", meaning: "環境", example: "We need to protect the environment." },
  { word: "nature", meaning: "自然", example: "I love spending time in nature." },
  { word: "weather", meaning: "天気", example: "The weather is nice today." },
  { word: "temperature", meaning: "気温・温度", example: "The temperature is 30 degrees today." },
  { word: "cloud", meaning: "雲", example: "There are dark clouds in the sky." },
  { word: "rain", meaning: "雨", example: "It will rain tomorrow." },
  { word: "snow", meaning: "雪", example: "The children are playing in the snow." },
  { word: "wind", meaning: "風", example: "The wind is very strong today." },
  { word: "storm", meaning: "嵐", example: "A big storm is coming tonight." },
  { word: "sunshine", meaning: "日光", example: "I enjoy the warm sunshine in the morning." },
  { word: "thunder", meaning: "雷", example: "I heard loud thunder last night." },
  { word: "rainbow", meaning: "虹", example: "We saw a beautiful rainbow after the rain." },
  { word: "forest", meaning: "森", example: "We went hiking in the forest." },
  { word: "mountain", meaning: "山", example: "That mountain is very high." },
  { word: "river", meaning: "川", example: "We swam in the river last summer." },
  { word: "ocean", meaning: "海・大洋", example: "The ocean looks so blue today." },
  { word: "lake", meaning: "湖", example: "We had a picnic by the lake." },
  { word: "island", meaning: "島", example: "They traveled to a small island." },
  { word: "desert", meaning: "砂漠", example: "The desert is very hot during the day." },
  { word: "field", meaning: "野原・畑", example: "The farmer works in the field every day." },
  { word: "garden", meaning: "庭", example: "She grows flowers in her garden." },
  { word: "plant", meaning: "植物", example: "This plant needs a lot of water." },
  { word: "flower", meaning: "花", example: "He gave her a bunch of flowers." },
  { word: "tree", meaning: "木", example: "There is a big tree in front of our house." },
  { word: "leaf", meaning: "葉", example: "The leaves turn red in autumn." },
  { word: "seed", meaning: "種", example: "She planted seeds in the garden." },
  { word: "soil", meaning: "土", example: "The soil here is very rich." },
  { word: "climate", meaning: "気候", example: "The climate is changing all over the world." },
  { word: "season", meaning: "季節", example: "Spring is my favorite season." },
  { word: "sunset", meaning: "夕日・日没", example: "We watched the sunset from the beach." },

  // --- Shopping & Money (281-310) ---
  { word: "price", meaning: "価格・値段", example: "What is the price of this shirt?" },
  { word: "cost", meaning: "費用・コスト", example: "The cost of living is high in this city." },
  { word: "discount", meaning: "割引", example: "There is a 20% discount on all shoes." },
  { word: "sale", meaning: "セール・販売", example: "The store is having a big sale this week." },
  { word: "customer", meaning: "客・顧客", example: "The customer asked for a refund." },
  { word: "receipt", meaning: "レシート・領収書", example: "Please keep your receipt." },
  { word: "cash", meaning: "現金", example: "I don't have enough cash with me." },
  { word: "credit", meaning: "クレジット・信用", example: "Can I pay by credit card?" },
  { word: "budget", meaning: "予算", example: "We need to stay within our budget." },
  { word: "expense", meaning: "支出・経費", example: "Travel is my biggest expense." },
  { word: "savings", meaning: "貯金", example: "She has a lot of savings in the bank." },
  { word: "tax", meaning: "税金", example: "The tax on this item is included in the price." },
  { word: "bill", meaning: "請求書・勘定", example: "Can I have the bill, please?" },
  { word: "coin", meaning: "硬貨・コイン", example: "I found a coin on the street." },
  { word: "wallet", meaning: "財布", example: "I left my wallet at home." },
  { word: "purchase", meaning: "購入", example: "Thank you for your purchase." },
  { word: "refund", meaning: "返金", example: "I would like to get a refund for this product." },
  { word: "bargain", meaning: "お買い得品・値切る", example: "This coat was a real bargain." },
  { word: "checkout", meaning: "レジ・会計", example: "Please go to the checkout counter." },
  { word: "brand", meaning: "ブランド・銘柄", example: "What brand of shoes do you prefer?" },
  { word: "quality", meaning: "品質", example: "This product is very high quality." },
  { word: "quantity", meaning: "量・数量", example: "We need a large quantity of paper." },
  { word: "delivery", meaning: "配達", example: "The delivery will arrive by Friday." },
  { word: "order", meaning: "注文", example: "I placed an order online yesterday." },
  { word: "exchange", meaning: "交換", example: "Can I exchange this for a larger size?" },
  { word: "market", meaning: "市場・マーケット", example: "We buy fresh vegetables at the market." },
  { word: "goods", meaning: "商品・品物", example: "The store sells many kinds of goods." },
  { word: "profit", meaning: "利益", example: "The company made a big profit this year." },
  { word: "loan", meaning: "ローン・貸付", example: "She took out a loan to buy a car." },
  { word: "invest", meaning: "投資する", example: "He decided to invest in stocks." },

  // --- Emotions & Feelings (311-340) ---
  { word: "happy", meaning: "幸せな・嬉しい", example: "I am so happy to see you again." },
  { word: "sad", meaning: "悲しい", example: "She felt sad when her friend moved away." },
  { word: "angry", meaning: "怒った", example: "He was angry about the late delivery." },
  { word: "afraid", meaning: "恐れている・怖い", example: "She is afraid of spiders." },
  { word: "excited", meaning: "わくわくした", example: "The kids are excited about the trip." },
  { word: "nervous", meaning: "緊張した", example: "I am nervous about the job interview." },
  { word: "surprised", meaning: "驚いた", example: "I was surprised by the news." },
  { word: "worried", meaning: "心配した", example: "She is worried about her exam results." },
  { word: "lonely", meaning: "寂しい・孤独な", example: "He felt lonely after moving to a new city." },
  { word: "proud", meaning: "誇りに思う", example: "I am proud of my daughter's success." },
  { word: "disappointed", meaning: "失望した・がっかりした", example: "She was disappointed with the test score." },
  { word: "jealous", meaning: "嫉妬した・うらやましい", example: "He is jealous of his brother's new car." },
  { word: "confident", meaning: "自信のある", example: "She feels confident about the presentation." },
  { word: "grateful", meaning: "感謝している", example: "I am grateful for your help." },
  { word: "confused", meaning: "混乱した", example: "I was confused by the instructions." },
  { word: "frustrated", meaning: "いらいらした", example: "He felt frustrated with the slow computer." },
  { word: "relaxed", meaning: "リラックスした", example: "I feel very relaxed after a hot bath." },
  { word: "bored", meaning: "退屈した", example: "The children were bored on the rainy day." },
  { word: "embarrassed", meaning: "恥ずかしい", example: "She was embarrassed when she tripped." },
  { word: "curious", meaning: "好奇心のある", example: "The child is curious about everything." },
  { word: "satisfied", meaning: "満足した", example: "I am satisfied with the results." },
  { word: "terrified", meaning: "恐怖を感じた", example: "She was terrified during the earthquake." },
  { word: "cheerful", meaning: "陽気な・明るい", example: "He is always cheerful in the morning." },
  { word: "anxious", meaning: "不安な", example: "I feel anxious before flying." },
  { word: "hopeful", meaning: "希望に満ちた", example: "We are hopeful about the future." },
  { word: "miserable", meaning: "惨めな・みじめな", example: "The cold weather made everyone miserable." },
  { word: "sympathy", meaning: "同情・共感", example: "I have great sympathy for the victims." },
  { word: "mood", meaning: "気分", example: "She is in a good mood today." },
  { word: "emotion", meaning: "感情", example: "He tried to hide his emotions." },
  { word: "stress", meaning: "ストレス", example: "Too much stress is bad for your health." },

  // --- Sports & Hobbies (341-370) ---
  { word: "exercise", meaning: "運動・エクササイズ", example: "I exercise every morning before work." },
  { word: "soccer", meaning: "サッカー", example: "He plays soccer every weekend." },
  { word: "baseball", meaning: "野球", example: "Baseball is very popular in Japan." },
  { word: "tennis", meaning: "テニス", example: "She takes tennis lessons on Saturdays." },
  { word: "swimming", meaning: "水泳", example: "Swimming is great exercise for the whole body." },
  { word: "running", meaning: "ランニング", example: "Running in the park is my daily routine." },
  { word: "basketball", meaning: "バスケットボール", example: "They play basketball after school." },
  { word: "yoga", meaning: "ヨガ", example: "She does yoga to stay flexible." },
  { word: "hiking", meaning: "ハイキング", example: "We went hiking in the mountains last weekend." },
  { word: "camping", meaning: "キャンプ", example: "Our family enjoys camping in the summer." },
  { word: "fishing", meaning: "釣り", example: "He goes fishing at the lake every Sunday." },
  { word: "painting", meaning: "絵を描くこと・絵画", example: "Painting is her favorite hobby." },
  { word: "photography", meaning: "写真撮影", example: "He is interested in photography." },
  { word: "gardening", meaning: "ガーデニング・園芸", example: "Gardening helps me relax on weekends." },
  { word: "cooking", meaning: "料理", example: "Cooking is both a hobby and a skill." },
  { word: "reading", meaning: "読書", example: "Reading before bed helps me fall asleep." },
  { word: "dancing", meaning: "ダンス・踊ること", example: "She loves dancing to pop music." },
  { word: "singing", meaning: "歌うこと", example: "Singing in the shower is fun." },
  { word: "cycling", meaning: "サイクリング", example: "Cycling along the river is very pleasant." },
  { word: "skiing", meaning: "スキー", example: "We go skiing in Nagano every winter." },
  { word: "surfing", meaning: "サーフィン", example: "Surfing is popular in Hawaii." },
  { word: "gym", meaning: "ジム", example: "I go to the gym three times a week." },
  { word: "match", meaning: "試合", example: "We watched an exciting match on TV." },
  { word: "score", meaning: "得点・スコア", example: "The final score was 3 to 1." },
  { word: "team", meaning: "チーム", example: "Our team won the championship." },
  { word: "coach", meaning: "コーチ・監督", example: "The coach gave us great advice." },
  { word: "practice", meaning: "練習", example: "Practice makes perfect." },
  { word: "tournament", meaning: "トーナメント・大会", example: "She entered a tennis tournament." },
  { word: "champion", meaning: "チャンピオン・優勝者", example: "He became the champion of the league." },
  { word: "athlete", meaning: "アスリート・運動選手", example: "She is a professional athlete." },

  // --- Technology & Media (371-400) ---
  { word: "internet", meaning: "インターネット", example: "The internet has changed our lives." },
  { word: "computer", meaning: "コンピュータ", example: "I use my computer for work every day." },
  { word: "smartphone", meaning: "スマートフォン", example: "Almost everyone has a smartphone now." },
  { word: "application", meaning: "アプリケーション・アプリ", example: "I downloaded a new application for learning English." },
  { word: "website", meaning: "ウェブサイト", example: "Please visit our website for more information." },
  { word: "software", meaning: "ソフトウェア", example: "We need to update the software." },
  { word: "hardware", meaning: "ハードウェア", example: "The hardware of this computer is very fast." },
  { word: "data", meaning: "データ", example: "We need to analyze the data carefully." },
  { word: "password", meaning: "パスワード", example: "Please enter your password to log in." },
  { word: "download", meaning: "ダウンロードする", example: "You can download the file from the website." },
  { word: "upload", meaning: "アップロードする", example: "Please upload your photo to the profile page." },
  { word: "search", meaning: "検索する", example: "I searched for the restaurant online." },
  { word: "click", meaning: "クリックする", example: "Click the button to submit the form." },
  { word: "screen", meaning: "画面・スクリーン", example: "The screen of my phone is cracked." },
  { word: "keyboard", meaning: "キーボード", example: "I need a new keyboard for my computer." },
  { word: "battery", meaning: "バッテリー・電池", example: "My phone battery is almost dead." },
  { word: "network", meaning: "ネットワーク", example: "The Wi-Fi network is very slow today." },
  { word: "online", meaning: "オンラインの", example: "I bought this book at an online store." },
  { word: "digital", meaning: "デジタルの", example: "We live in a digital age." },
  { word: "video", meaning: "動画・ビデオ", example: "She posted a video on social media." },
  { word: "camera", meaning: "カメラ", example: "He bought a new camera for his trip." },
  { word: "program", meaning: "プログラム", example: "She learned to write a computer program." },
  { word: "device", meaning: "デバイス・機器", example: "This device is very easy to use." },
  { word: "message", meaning: "メッセージ", example: "I sent a message to my friend." },
  { word: "social media", meaning: "ソーシャルメディア・SNS", example: "Many people use social media every day." },
  { word: "notification", meaning: "通知", example: "I got a notification from the app." },
  { word: "update", meaning: "更新・アップデート", example: "Please update your app to the latest version." },
  { word: "streaming", meaning: "ストリーミング", example: "We watched a movie on a streaming service." },
  { word: "podcast", meaning: "ポッドキャスト", example: "I listen to a podcast on my way to work." },
  { word: "artificial intelligence", meaning: "人工知能・AI", example: "Artificial intelligence is changing many industries." },

  // --- City & Places (401-430) ---
  { word: "city", meaning: "都市・市", example: "Tokyo is a very big city." },
  { word: "town", meaning: "町", example: "She grew up in a small town." },
  { word: "village", meaning: "村", example: "The village is surrounded by mountains." },
  { word: "neighborhood", meaning: "近所・地域", example: "This is a quiet neighborhood." },
  { word: "street", meaning: "通り・道", example: "The street was crowded with people." },
  { word: "bridge", meaning: "橋", example: "We walked across the old bridge." },
  { word: "building", meaning: "建物・ビル", example: "That building is the tallest in the city." },
  { word: "apartment", meaning: "アパート・マンション", example: "She lives in a small apartment downtown." },
  { word: "factory", meaning: "工場", example: "The factory produces cars." },
  { word: "museum", meaning: "博物館・美術館", example: "We visited the art museum on Sunday." },
  { word: "library", meaning: "図書館", example: "I study at the library every evening." },
  { word: "hospital", meaning: "病院", example: "She was taken to the hospital by ambulance." },
  { word: "pharmacy", meaning: "薬局", example: "I need to go to the pharmacy to buy medicine." },
  { word: "temple", meaning: "寺院", example: "We visited a famous temple in Kyoto." },
  { word: "church", meaning: "教会", example: "The church has a beautiful bell tower." },
  { word: "park", meaning: "公園", example: "The children play in the park after school." },
  { word: "stadium", meaning: "スタジアム・競技場", example: "The stadium was full of fans." },
  { word: "theater", meaning: "劇場・映画館", example: "We watched a play at the theater." },
  { word: "zoo", meaning: "動物園", example: "The children love going to the zoo." },
  { word: "airport", meaning: "空港", example: "We arrived at the airport two hours early." },
  { word: "station", meaning: "駅", example: "The station is just five minutes from here." },
  { word: "harbor", meaning: "港", example: "The harbor was full of fishing boats." },
  { word: "suburb", meaning: "郊外", example: "They moved to the suburbs last year." },
  { word: "downtown", meaning: "繁華街・中心街", example: "Let's go shopping downtown this weekend." },
  { word: "intersection", meaning: "交差点", example: "Turn left at the next intersection." },
  { word: "sidewalk", meaning: "歩道", example: "Please walk on the sidewalk." },
  { word: "parking lot", meaning: "駐車場", example: "The parking lot is behind the building." },
  { word: "landmark", meaning: "ランドマーク・目印", example: "The tower is a famous landmark in this city." },
  { word: "monument", meaning: "記念碑・モニュメント", example: "We took photos in front of the monument." },
  { word: "fountain", meaning: "噴水", example: "There is a beautiful fountain in the square." },

  // --- Actions & Verbs (431-460) ---
  { word: "achieve", meaning: "達成する", example: "She achieved her goal of running a marathon." },
  { word: "improve", meaning: "改善する・上達する", example: "I want to improve my English skills." },
  { word: "develop", meaning: "発展させる・開発する", example: "The company is developing a new product." },
  { word: "communicate", meaning: "伝える・コミュニケーションする", example: "It is important to communicate clearly." },
  { word: "organize", meaning: "整理する・組織する", example: "She organized the files on her desk." },
  { word: "compete", meaning: "競争する", example: "They compete against each other in the race." },
  { word: "create", meaning: "作り出す・創造する", example: "He created a beautiful painting." },
  { word: "discover", meaning: "発見する", example: "Scientists discovered a new planet." },
  { word: "explore", meaning: "探検する・探る", example: "We explored the old castle together." },
  { word: "imagine", meaning: "想像する", example: "Can you imagine living on Mars?" },
  { word: "introduce", meaning: "紹介する", example: "Let me introduce you to my colleague." },
  { word: "mention", meaning: "言及する・述べる", example: "He mentioned the meeting in his email." },
  { word: "provide", meaning: "提供する", example: "The hotel provides free breakfast." },
  { word: "suggest", meaning: "提案する", example: "I suggest we leave early to avoid traffic." },
  { word: "recognize", meaning: "認識する・見分ける", example: "I didn't recognize her with short hair." },
  { word: "consider", meaning: "検討する・考慮する", example: "Please consider my proposal carefully." },
  { word: "compare", meaning: "比較する", example: "Let's compare the prices of both products." },
  { word: "separate", meaning: "分ける・離す", example: "Please separate the recyclables from the trash." },
  { word: "combine", meaning: "組み合わせる", example: "Combine the ingredients in a large bowl." },
  { word: "require", meaning: "必要とする・要求する", example: "This job requires strong communication skills." },
  { word: "include", meaning: "含む", example: "The price includes tax." },
  { word: "reduce", meaning: "減らす", example: "We need to reduce our expenses." },
  { word: "increase", meaning: "増やす・増加する", example: "The company increased its sales this year." },
  { word: "encourage", meaning: "励ます・勧める", example: "My teacher encouraged me to study abroad." },
  { word: "prepare", meaning: "準備する", example: "She prepared dinner for the family." },
  { word: "protect", meaning: "守る・保護する", example: "We must protect our environment." },
  { word: "deliver", meaning: "届ける・配達する", example: "The package was delivered this morning." },
  { word: "select", meaning: "選ぶ・選択する", example: "Please select your preferred date." },
  { word: "attract", meaning: "引きつける・魅了する", example: "The festival attracts many tourists." },
  { word: "support", meaning: "支える・支援する", example: "My family always supports me." },

  // --- Adjectives & Descriptions (461-490) ---
  { word: "comfortable", meaning: "快適な", example: "This chair is very comfortable." },
  { word: "convenient", meaning: "便利な", example: "The location is very convenient for shopping." },
  { word: "essential", meaning: "不可欠な・必要な", example: "Water is essential for life." },
  { word: "available", meaning: "利用可能な・空いている", example: "Is this seat available?" },
  { word: "necessary", meaning: "必要な", example: "It is necessary to bring your passport." },
  { word: "possible", meaning: "可能な", example: "Is it possible to change the reservation?" },
  { word: "impossible", meaning: "不可能な", example: "Nothing is impossible if you try hard enough." },
  { word: "recent", meaning: "最近の", example: "I read about it in a recent article." },
  { word: "popular", meaning: "人気のある", example: "This restaurant is very popular among tourists." },
  { word: "famous", meaning: "有名な", example: "Kyoto is famous for its temples." },
  { word: "excellent", meaning: "素晴らしい・優秀な", example: "The food at this restaurant is excellent." },
  { word: "incredible", meaning: "信じられない・素晴らしい", example: "The view from the top was incredible." },
  { word: "awful", meaning: "ひどい", example: "The weather was awful yesterday." },
  { word: "huge", meaning: "巨大な", example: "They live in a huge house." },
  { word: "tiny", meaning: "とても小さい", example: "She has a tiny dog." },
  { word: "narrow", meaning: "狭い・細い", example: "The street is too narrow for cars." },
  { word: "broad", meaning: "広い・幅広い", example: "He has a broad knowledge of history." },
  { word: "smooth", meaning: "滑らかな", example: "The surface of the table is very smooth." },
  { word: "rough", meaning: "粗い・荒い", example: "The road was rough and bumpy." },
  { word: "plain", meaning: "質素な・地味な", example: "She wore a plain white dress." },
  { word: "gentle", meaning: "優しい・穏やかな", example: "He is a very gentle person." },
  { word: "fierce", meaning: "激しい・獰猛な", example: "The competition was fierce." },
  { word: "typical", meaning: "典型的な", example: "This is a typical Japanese breakfast." },
  { word: "unique", meaning: "ユニークな・独特の", example: "Each person has a unique personality." },
  { word: "entire", meaning: "全体の・全部の", example: "I spent the entire day studying." },
  { word: "various", meaning: "さまざまな", example: "The store sells various kinds of cheese." },
  { word: "specific", meaning: "具体的な・特定の", example: "Do you have a specific question?" },
  { word: "appropriate", meaning: "適切な", example: "Please wear appropriate clothes for the event." },
  { word: "valuable", meaning: "貴重な・価値のある", example: "Thank you for your valuable advice." },
  { word: "ordinary", meaning: "普通の・平凡な", example: "It was just an ordinary day." },

  // --- Adverbs & Connectors (491-500) ---
  { word: "however", meaning: "しかしながら", example: "It was raining. However, we still went out." },
  { word: "therefore", meaning: "したがって", example: "He was sick. Therefore, he stayed home." },
  { word: "moreover", meaning: "さらに・その上", example: "The hotel is cheap. Moreover, it is very clean." },
  { word: "otherwise", meaning: "さもなければ", example: "Hurry up, otherwise we will be late." },
  { word: "meanwhile", meaning: "その間に", example: "I will cook dinner. Meanwhile, please set the table." },
  { word: "furthermore", meaning: "さらに・そのうえ", example: "The plan is effective. Furthermore, it is affordable." },
  { word: "instead", meaning: "代わりに", example: "I didn't take the bus. Instead, I walked." },
  { word: "especially", meaning: "特に", example: "I love fruit, especially strawberries." },
  { word: "actually", meaning: "実は・実際に", example: "Actually, I have never been to Osaka." },
  { word: "eventually", meaning: "最終的に・結局", example: "We eventually found the restaurant after getting lost." }
];
