const wordData1 = [
  // === 1. Basic greetings & common expressions (1-30) ===
  { word: "hello", meaning: "こんにちは", example: "Hello, how are you today?" },
  { word: "goodbye", meaning: "さようなら", example: "Goodbye, see you tomorrow!" },
  { word: "thank you", meaning: "ありがとう", example: "Thank you for your help." },
  { word: "please", meaning: "お願いします／どうぞ", example: "Please sit down." },
  { word: "sorry", meaning: "ごめんなさい", example: "I'm sorry for being late." },
  { word: "excuse me", meaning: "すみません", example: "Excuse me, where is the station?" },
  { word: "yes", meaning: "はい", example: "Yes, I understand." },
  { word: "no", meaning: "いいえ", example: "No, thank you. I'm fine." },
  { word: "good morning", meaning: "おはようございます", example: "Good morning! Did you sleep well?" },
  { word: "good night", meaning: "おやすみなさい", example: "Good night, sweet dreams." },
  { word: "welcome", meaning: "ようこそ／歓迎", example: "Welcome to our school!" },
  { word: "congratulations", meaning: "おめでとうございます", example: "Congratulations on your graduation!" },
  { word: "nice", meaning: "素敵な／良い", example: "It's a nice day today." },
  { word: "great", meaning: "素晴らしい", example: "You did a great job!" },
  { word: "happy", meaning: "幸せな／嬉しい", example: "I'm so happy to see you." },
  { word: "sad", meaning: "悲しい", example: "She looks sad today." },
  { word: "angry", meaning: "怒っている", example: "He was angry about the mistake." },
  { word: "tired", meaning: "疲れた", example: "I'm tired after a long day." },
  { word: "hungry", meaning: "お腹が空いた", example: "I'm hungry. Let's eat lunch." },
  { word: "thirsty", meaning: "喉が渇いた", example: "I'm thirsty. Can I have some water?" },
  { word: "help", meaning: "助ける／助け", example: "Can you help me with this?" },
  { word: "understand", meaning: "理解する", example: "I understand what you mean." },
  { word: "know", meaning: "知っている", example: "Do you know his name?" },
  { word: "want", meaning: "欲しい／〜したい", example: "I want to learn English." },
  { word: "need", meaning: "必要とする", example: "I need your advice." },
  { word: "like", meaning: "好き／〜のような", example: "I like reading books." },
  { word: "love", meaning: "愛する／大好き", example: "I love my family very much." },
  { word: "friend", meaning: "友達", example: "She is my best friend." },
  { word: "name", meaning: "名前", example: "My name is Yuki." },
  { word: "today", meaning: "今日", example: "What are you doing today?" },

  // === 2. Numbers, time, days (31-50) ===
  { word: "number", meaning: "数字／番号", example: "What is your phone number?" },
  { word: "zero", meaning: "ゼロ", example: "The temperature dropped to zero." },
  { word: "hundred", meaning: "百", example: "There are one hundred students in the school." },
  { word: "thousand", meaning: "千", example: "This bag costs two thousand yen." },
  { word: "time", meaning: "時間／時刻", example: "What time is it now?" },
  { word: "morning", meaning: "朝", example: "I go jogging every morning." },
  { word: "afternoon", meaning: "午後", example: "We have a meeting this afternoon." },
  { word: "evening", meaning: "夕方／晩", example: "Let's have dinner this evening." },
  { word: "night", meaning: "夜", example: "The stars are beautiful at night." },
  { word: "hour", meaning: "時間（1時間）", example: "The meeting will last about one hour." },
  { word: "tomorrow", meaning: "明日", example: "I will call you tomorrow." },
  { word: "yesterday", meaning: "昨日", example: "I met him yesterday." },
  { word: "week", meaning: "週", example: "I exercise three times a week." },
  { word: "month", meaning: "月（期間）", example: "I've been here for two months." },
  { word: "year", meaning: "年", example: "This year has been wonderful." },
  { word: "Monday", meaning: "月曜日", example: "The meeting is on Monday." },
  { word: "weekend", meaning: "週末", example: "What are your plans for the weekend?" },
  { word: "holiday", meaning: "休日／祝日", example: "We have a holiday next week." },
  { word: "birthday", meaning: "誕生日", example: "Happy birthday! How old are you?" },
  { word: "clock", meaning: "時計", example: "The clock on the wall says three o'clock." },

  // === 3. Family & people (51-70) ===
  { word: "family", meaning: "家族", example: "My family has five members." },
  { word: "mother", meaning: "母", example: "My mother is a great cook." },
  { word: "father", meaning: "父", example: "My father works at a bank." },
  { word: "parents", meaning: "両親", example: "My parents live in Osaka." },
  { word: "brother", meaning: "兄／弟", example: "My brother is older than me." },
  { word: "sister", meaning: "姉／妹", example: "My sister studies at university." },
  { word: "child", meaning: "子供", example: "The child is playing in the park." },
  { word: "children", meaning: "子供たち", example: "The children are having fun." },
  { word: "baby", meaning: "赤ちゃん", example: "The baby is sleeping quietly." },
  { word: "husband", meaning: "夫", example: "Her husband is a kind person." },
  { word: "wife", meaning: "妻", example: "His wife is a doctor." },
  { word: "grandfather", meaning: "祖父", example: "My grandfather is ninety years old." },
  { word: "grandmother", meaning: "祖母", example: "My grandmother makes delicious cookies." },
  { word: "uncle", meaning: "おじ", example: "My uncle lives in America." },
  { word: "aunt", meaning: "おば", example: "My aunt visits us every summer." },
  { word: "cousin", meaning: "いとこ", example: "My cousin and I are the same age." },
  { word: "neighbor", meaning: "隣人／近所の人", example: "Our neighbor is very friendly." },
  { word: "person", meaning: "人", example: "She is a very kind person." },
  { word: "people", meaning: "人々", example: "Many people came to the festival." },
  { word: "boy", meaning: "男の子", example: "The boy is riding a bicycle." },

  // === 4. Food & drink (71-100) ===
  { word: "food", meaning: "食べ物", example: "Japanese food is very popular." },
  { word: "drink", meaning: "飲む／飲み物", example: "What would you like to drink?" },
  { word: "water", meaning: "水", example: "Can I have a glass of water?" },
  { word: "tea", meaning: "お茶", example: "Would you like some green tea?" },
  { word: "coffee", meaning: "コーヒー", example: "I drink coffee every morning." },
  { word: "milk", meaning: "牛乳", example: "Children should drink milk every day." },
  { word: "juice", meaning: "ジュース", example: "I'd like a glass of orange juice." },
  { word: "rice", meaning: "ご飯／米", example: "We eat rice every day in Japan." },
  { word: "bread", meaning: "パン", example: "I had bread and butter for breakfast." },
  { word: "egg", meaning: "卵", example: "I eat a boiled egg for breakfast." },
  { word: "meat", meaning: "肉", example: "I don't eat much meat." },
  { word: "chicken", meaning: "鶏肉／鶏", example: "We had grilled chicken for dinner." },
  { word: "fish", meaning: "魚", example: "Fresh fish is delicious." },
  { word: "vegetable", meaning: "野菜", example: "You should eat more vegetables." },
  { word: "fruit", meaning: "果物", example: "I like to eat fresh fruit." },
  { word: "apple", meaning: "りんご", example: "She ate an apple after lunch." },
  { word: "banana", meaning: "バナナ", example: "Bananas are a good snack." },
  { word: "orange", meaning: "オレンジ", example: "This orange is very sweet." },
  { word: "sugar", meaning: "砂糖", example: "Do you take sugar in your coffee?" },
  { word: "salt", meaning: "塩", example: "Please pass the salt." },
  { word: "pepper", meaning: "コショウ", example: "Add some pepper to the soup." },
  { word: "soup", meaning: "スープ", example: "This soup is very hot." },
  { word: "salad", meaning: "サラダ", example: "I'll have a salad for lunch." },
  { word: "cake", meaning: "ケーキ", example: "She baked a chocolate cake." },
  { word: "breakfast", meaning: "朝食", example: "Breakfast is the most important meal." },
  { word: "lunch", meaning: "昼食", example: "Let's have lunch together." },
  { word: "dinner", meaning: "夕食", example: "What's for dinner tonight?" },
  { word: "restaurant", meaning: "レストラン", example: "Let's go to a restaurant this evening." },
  { word: "menu", meaning: "メニュー", example: "May I see the menu, please?" },
  { word: "delicious", meaning: "おいしい", example: "This pasta is really delicious." },

  // === 5. Body & health (101-130) ===
  { word: "body", meaning: "体", example: "Exercise is good for your body." },
  { word: "head", meaning: "頭", example: "I have a headache. My head hurts." },
  { word: "face", meaning: "顔", example: "She has a beautiful face." },
  { word: "eye", meaning: "目", example: "She has big brown eyes." },
  { word: "ear", meaning: "耳", example: "I have an earache in my left ear." },
  { word: "nose", meaning: "鼻", example: "My nose is running because of my cold." },
  { word: "mouth", meaning: "口", example: "Open your mouth wide, please." },
  { word: "tooth", meaning: "歯", example: "I brush my teeth three times a day." },
  { word: "hand", meaning: "手", example: "Please wash your hands before eating." },
  { word: "finger", meaning: "指", example: "I cut my finger while cooking." },
  { word: "arm", meaning: "腕", example: "He broke his arm playing soccer." },
  { word: "leg", meaning: "脚", example: "My leg hurts after running." },
  { word: "foot", meaning: "足（先）", example: "I walked so much that my feet are sore." },
  { word: "back", meaning: "背中／戻る", example: "My back hurts from sitting all day." },
  { word: "heart", meaning: "心臓／心", example: "Exercise keeps your heart healthy." },
  { word: "stomach", meaning: "胃／お腹", example: "I have a stomachache." },
  { word: "health", meaning: "健康", example: "Health is more important than money." },
  { word: "healthy", meaning: "健康な", example: "Eating vegetables keeps you healthy." },
  { word: "sick", meaning: "病気の", example: "I was sick last week." },
  { word: "cold", meaning: "風邪／寒い", example: "I caught a cold yesterday." },
  { word: "fever", meaning: "熱", example: "She has a high fever." },
  { word: "pain", meaning: "痛み", example: "I feel a sharp pain in my back." },
  { word: "medicine", meaning: "薬", example: "Take this medicine after meals." },
  { word: "doctor", meaning: "医者", example: "You should see a doctor." },
  { word: "hospital", meaning: "病院", example: "He was taken to the hospital." },
  { word: "nurse", meaning: "看護師", example: "The nurse took my temperature." },
  { word: "exercise", meaning: "運動する／運動", example: "I exercise for thirty minutes every day." },
  { word: "sleep", meaning: "眠る／睡眠", example: "I need at least seven hours of sleep." },
  { word: "rest", meaning: "休む／休息", example: "You should rest if you feel tired." },
  { word: "strong", meaning: "強い", example: "He is strong enough to carry that box." },

  // === 6. Home & daily life (131-160) ===
  { word: "home", meaning: "家／自宅", example: "I usually get home at six." },
  { word: "house", meaning: "家（建物）", example: "They bought a new house last year." },
  { word: "room", meaning: "部屋", example: "My room is on the second floor." },
  { word: "kitchen", meaning: "台所", example: "She is cooking in the kitchen." },
  { word: "bathroom", meaning: "浴室／トイレ", example: "The bathroom is down the hall." },
  { word: "bedroom", meaning: "寝室", example: "The bedroom has a large window." },
  { word: "door", meaning: "ドア", example: "Please close the door." },
  { word: "window", meaning: "窓", example: "Can you open the window?" },
  { word: "table", meaning: "テーブル", example: "Put the dishes on the table." },
  { word: "chair", meaning: "椅子", example: "Please sit in this chair." },
  { word: "bed", meaning: "ベッド", example: "I go to bed at eleven every night." },
  { word: "cook", meaning: "料理する／料理人", example: "I like to cook on weekends." },
  { word: "clean", meaning: "掃除する／きれいな", example: "I clean my room every Saturday." },
  { word: "wash", meaning: "洗う", example: "I need to wash the dishes." },
  { word: "clothes", meaning: "衣服", example: "I need to buy new clothes." },
  { word: "shirt", meaning: "シャツ", example: "He is wearing a white shirt." },
  { word: "shoes", meaning: "靴", example: "Take off your shoes at the entrance." },
  { word: "bag", meaning: "かばん", example: "I put my books in my bag." },
  { word: "key", meaning: "鍵", example: "Don't forget your key." },
  { word: "phone", meaning: "電話", example: "My phone is ringing." },
  { word: "television", meaning: "テレビ", example: "We watch television after dinner." },
  { word: "computer", meaning: "コンピューター", example: "I use a computer for work." },
  { word: "internet", meaning: "インターネット", example: "The internet connection is slow today." },
  { word: "morning routine", meaning: "朝の習慣", example: "My morning routine starts with coffee." },
  { word: "shower", meaning: "シャワー", example: "I take a shower every morning." },
  { word: "towel", meaning: "タオル", example: "Please hand me a towel." },
  { word: "garden", meaning: "庭", example: "She grows flowers in the garden." },
  { word: "pet", meaning: "ペット", example: "Do you have any pets?" },
  { word: "dog", meaning: "犬", example: "I walk my dog every evening." },
  { word: "cat", meaning: "猫", example: "The cat is sleeping on the sofa." },

  // === 7. School & education (161-190) ===
  { word: "school", meaning: "学校", example: "I go to school by bus." },
  { word: "student", meaning: "学生／生徒", example: "She is a university student." },
  { word: "teacher", meaning: "先生", example: "Our teacher is very kind." },
  { word: "class", meaning: "授業／クラス", example: "English class starts at nine." },
  { word: "classroom", meaning: "教室", example: "The classroom is on the third floor." },
  { word: "lesson", meaning: "授業／レッスン", example: "Today's lesson was very interesting." },
  { word: "homework", meaning: "宿題", example: "I have a lot of homework tonight." },
  { word: "test", meaning: "テスト／試験", example: "We have a math test tomorrow." },
  { word: "exam", meaning: "試験", example: "The final exam is next week." },
  { word: "study", meaning: "勉強する", example: "I study English every day." },
  { word: "learn", meaning: "学ぶ", example: "I want to learn a new language." },
  { word: "read", meaning: "読む", example: "I read a book before bed." },
  { word: "write", meaning: "書く", example: "Please write your name here." },
  { word: "speak", meaning: "話す", example: "Can you speak English?" },
  { word: "listen", meaning: "聴く", example: "Listen to the teacher carefully." },
  { word: "question", meaning: "質問", example: "Do you have any questions?" },
  { word: "answer", meaning: "答え／答える", example: "I know the answer to this question." },
  { word: "book", meaning: "本", example: "This book is very interesting." },
  { word: "notebook", meaning: "ノート", example: "I write notes in my notebook." },
  { word: "pen", meaning: "ペン", example: "May I borrow your pen?" },
  { word: "dictionary", meaning: "辞書", example: "Look up the word in the dictionary." },
  { word: "library", meaning: "図書館", example: "I go to the library on weekends." },
  { word: "university", meaning: "大学", example: "She graduated from a famous university." },
  { word: "subject", meaning: "科目／話題", example: "What is your favorite subject?" },
  { word: "math", meaning: "数学", example: "Math is my favorite subject." },
  { word: "science", meaning: "科学／理科", example: "I enjoy studying science." },
  { word: "history", meaning: "歴史", example: "I love learning about Japanese history." },
  { word: "English", meaning: "英語", example: "English is spoken in many countries." },
  { word: "grade", meaning: "成績／学年", example: "She got a good grade on the test." },
  { word: "graduate", meaning: "卒業する", example: "I will graduate from college next year." },

  // === 8. Work & business (191-220) ===
  { word: "work", meaning: "仕事／働く", example: "I work from nine to five." },
  { word: "job", meaning: "仕事／職", example: "He found a new job last month." },
  { word: "office", meaning: "オフィス／事務所", example: "I go to the office every weekday." },
  { word: "company", meaning: "会社", example: "She works for a large company." },
  { word: "business", meaning: "ビジネス／事業", example: "He started his own business." },
  { word: "meeting", meaning: "会議", example: "We have a meeting at ten o'clock." },
  { word: "boss", meaning: "上司", example: "My boss is very supportive." },
  { word: "colleague", meaning: "同僚", example: "I had lunch with my colleague." },
  { word: "customer", meaning: "顧客／お客様", example: "The customer is always right." },
  { word: "project", meaning: "プロジェクト", example: "We finished the project on time." },
  { word: "schedule", meaning: "スケジュール／予定", example: "What is your schedule for tomorrow?" },
  { word: "email", meaning: "メール", example: "I will send you an email later." },
  { word: "telephone", meaning: "電話", example: "I received a telephone call from the client." },
  { word: "report", meaning: "報告書／報告する", example: "Please submit the report by Friday." },
  { word: "document", meaning: "書類", example: "Please sign this document." },
  { word: "presentation", meaning: "プレゼンテーション", example: "She gave an excellent presentation." },
  { word: "deadline", meaning: "締め切り", example: "The deadline is next Monday." },
  { word: "salary", meaning: "給料", example: "He is happy with his salary." },
  { word: "interview", meaning: "面接", example: "I have a job interview tomorrow." },
  { word: "experience", meaning: "経験", example: "She has ten years of experience." },
  { word: "skill", meaning: "技術／スキル", example: "Communication skills are very important." },
  { word: "career", meaning: "キャリア／経歴", example: "She built a successful career." },
  { word: "manager", meaning: "マネージャー／管理者", example: "The manager approved the plan." },
  { word: "department", meaning: "部署／部門", example: "He works in the sales department." },
  { word: "contract", meaning: "契約", example: "We signed a new contract." },
  { word: "profit", meaning: "利益", example: "The company made a good profit this year." },
  { word: "goal", meaning: "目標", example: "What is your goal for this year?" },
  { word: "success", meaning: "成功", example: "Hard work is the key to success." },
  { word: "problem", meaning: "問題", example: "We need to solve this problem quickly." },
  { word: "solution", meaning: "解決策", example: "We found a good solution." },

  // === 9. Travel & transportation (221-250) ===
  { word: "travel", meaning: "旅行する", example: "I love to travel abroad." },
  { word: "trip", meaning: "旅行", example: "We are planning a trip to Kyoto." },
  { word: "vacation", meaning: "休暇", example: "I'm going on vacation next month." },
  { word: "airport", meaning: "空港", example: "We arrived at the airport two hours early." },
  { word: "airplane", meaning: "飛行機", example: "The airplane will depart at noon." },
  { word: "train", meaning: "電車", example: "I take the train to work every day." },
  { word: "station", meaning: "駅", example: "The station is a five-minute walk from here." },
  { word: "bus", meaning: "バス", example: "The bus comes every fifteen minutes." },
  { word: "taxi", meaning: "タクシー", example: "Let's take a taxi to the hotel." },
  { word: "car", meaning: "車", example: "He drives his car to work." },
  { word: "bicycle", meaning: "自転車", example: "I ride my bicycle to school." },
  { word: "ticket", meaning: "切符／チケット", example: "I bought a round-trip ticket." },
  { word: "passport", meaning: "パスポート", example: "Don't forget your passport." },
  { word: "hotel", meaning: "ホテル", example: "We stayed at a nice hotel." },
  { word: "reservation", meaning: "予約", example: "I made a reservation for two nights." },
  { word: "map", meaning: "地図", example: "Can I see a map of this area?" },
  { word: "suitcase", meaning: "スーツケース", example: "My suitcase is very heavy." },
  { word: "luggage", meaning: "荷物", example: "Please keep an eye on your luggage." },
  { word: "foreign", meaning: "外国の", example: "She speaks three foreign languages." },
  { word: "country", meaning: "国", example: "Which country do you want to visit?" },
  { word: "city", meaning: "都市／市", example: "Tokyo is a very large city." },
  { word: "road", meaning: "道路", example: "The road was closed due to construction." },
  { word: "street", meaning: "通り／街路", example: "Walk down this street for two blocks." },
  { word: "bridge", meaning: "橋", example: "We crossed the bridge over the river." },
  { word: "direction", meaning: "方向／道順", example: "Can you give me directions to the museum?" },
  { word: "arrive", meaning: "到着する", example: "We will arrive at the hotel by noon." },
  { word: "depart", meaning: "出発する", example: "The train departs at eight thirty." },
  { word: "check in", meaning: "チェックインする", example: "We need to check in before three o'clock." },
  { word: "tour", meaning: "ツアー／観光", example: "We took a guided tour of the castle." },
  { word: "souvenir", meaning: "お土産", example: "I bought a souvenir for my family." }
];
